#os:
# - linux
# - osx

dist: xenial
git:
  quiet: true
language: python
#python:
#  - '3.6'
#  - '3.7'
  #  # https://github.com/travis-ci/travis-ci/issues/9815
  #  dist: xenial
  #  sudo: true
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
matrix:
  include:
    #--------------------------------------------------------------------------------------------------
      # latest versions of package
    - name: "Python nightly (3.8)"  # 3.8 dev branch
      python: 'nightly'
      env:
      - PKGS='psutil'

    - name: "Python 3.7"
      python: '3.7'
      env:
      - PKGS='psutil'

    - name: "Python 3.6"
      python: '3.6'
      env:
      - PKGS='psutil'

    #--------------------------------------------------------------------------------------------------
      # without psutil
    - name: "Python nightly (3.8)"
      python: 'nightly'
      env:
      - PKGS=''

    - name: "Python 3.7"
      python: '3.7'
      env:
      - PKGS=''

    - name: "Python 3.6"
      python: '3.6'
      env:
      - PKGS=''

#-------------------------------------------------
# per https://gist.github.com/dan-blanchard/7045057

#notifications:
#  email: false


# per http://conda.pydata.org/docs/travis.html
install:
  - echo "python=$TRAVIS_PYTHON_VERSION ${PKGS}"
  - sudo apt-get update

  # if line per https://docs.travis-ci.com/user/multi-os/
  - echo "python version=$TRAVIS_PYTHON_VERSION"

#===install dependencies===
#-----------pip------------
  - if [ ${PKGS} != "" ];
        then python pip install ${PKGS}; 
    fi
  - pip list
#----------run-----------
  - python setup.py develop


# Run test
script:
  #- nosetests --with-cov --cov YOUR_PACKAGE_NAME_HERE --cov-config .coveragerc --logging-level=INFO
  - coverage run cpylog/test_log.py

  # good
  #- "python pyNastran/all_tests.py"
  #- "python -m coverage run pyNastran/all_tests_no_gui.py"

  # good
  #- "coverage run pyNastran/all_tests_no_gui.py"

# https://github.com/z4r/python-coveralls
# Calculate coverage
after_success:
#  - coveralls
  - codecov
#after_success:
#  - coveralls --config_file .coveragerc
